### ISSUE TITLE
Proper setup

### ISSUE THREAD

**Issue by wault** [wault/lights#2]
- <strike>Pip (+setup.py) </strike>

-  <strike>external dependencies from letsroll.py </strike>

- <strike>virtualenv must be client's responsibility</strike>

- <strike> requirements.txt</strike>

- <strike>deal w/ relative imports (?)</strike>

- css/js minifier - to setup.py or starter.py

**Comment by wault** [comment]
Also, think about autogenerating nginx's configuration

**Comment by wault** [comment]
Would make sense to make *starter.py* globally available (setup.py?)

**Comment by wault** [comment]
CLI via IPython? YAY 🙌

**Comment by wault** [comment]
Where to put bottle.py?

**Comment by vaultah** [comment]
Path to nginx config directory and executable -> lights config

**Comment by vaultah** [comment]
*starter.py* -> *setup.py run*

CLI via IPython will have to wait

Minifiers can (and will be added later)

Closing the issue
